### ISSUE TITLE
Are the procedures of weights aggregation and clients selection correct?

### ISSUE THREAD

**Issue by ddayzzz** [litian96/FedProx#10]
Good job. I have read the paper and codes. I have some questions:
- Weights aggregation didn't scale the sum of each weight by 1/K in codes: [fedbase.py line 115](https://github.com/litian96/FedProx/blob/b5a92e2d1eec0a450525bc911d7ba988b4468a3f/flearn/trainers/fedbase.py#L115)
- As you mention in paper, the target clients are chosen by their probability (p_k). But I found the relevant codes in [fedbase.py line98](https://github.com/litian96/FedProx/blob/b5a92e2d1eec0a450525bc911d7ba988b4468a3f/flearn/trainers/fedbase.py#L98) just uniformly chose the clients which is violated to the FedProx pseudo codes.
![来自剪切板的图片 20200504215401](https://user-images.githubusercontent.com/22568844/80973311-c8c3ed00-8e51-11ea-8974-875ba5cc0fd2.jpg)

Thank you.

**Comment by litian96** [comment]
Thanks for your questions!

There are at least two sampling schemes we can consider in this problem: (1) sampling devices with weights proportional to the number of local data points and simply averaging the updates, and (2) sampling devices uniformly and doing weighted aggregation with weights proportional to the number of local data points. In order to perform a fair comparison with FedAvg, we use the second scheme, which is slightly different from our algorithm (see Section 5.1 -- Implementation of the [paper](https://arxiv.org/pdf/1812.06127.pdf)). 

Interestingly, the proposed algorithm (using the first sampling scheme) performs slightly better for both FedProx and FedAvg (see Figure 12 in Appendix C.3.4).

That's a good point. Please let me know if you have other questions!

**Comment by ddayzzz** [comment]
> Thanks for your questions!
> 
> There are at least two sampling schemes we can consider in this problem: (1) sampling devices with weights proportional to the number of local data points and simply averaging the updates, and (2) sampling devices uniformly and doing weighted aggregation with weights proportional to the number of local data points. In order to perform a fair comparison with FedAvg, we use the second scheme, which is slightly different from our algorithm (see Section 5.1 -- Implementation of the [paper](https://arxiv.org/pdf/1812.06127.pdf)).
> 
> Interestingly, the proposed algorithm (using the first sampling scheme) performs slightly better for both FedProx and FedAvg (see Figure 12 in Appendix C.3.4).
> 
> That's a good point. Please let me know if you have other questions!

Thank you for your reply. I have implemented the schemes following your instruction. I have another question: Did you consider the system heterogeneity when compare the differences between scheme 1 and 2?

**Comment by litian96** [comment]
For Figure 12 in Appendix C.3.4, no. But you can always do that, just that we were concerned about the statistical efficiency of different sampling schemes, so we didn't mix it with the systems heterogeneity. And Fedprox is agnostic of the sampling schemes and can yield similar improvement under either scenario.

**Comment by ddayzzz** [comment]
> For Figure 12 in Appendix C.3.4, no. But you can always do that, just that we were concerned about the statistical efficiency of different sampling schemes, so we didn't mix it with the systems heterogeneity. And Fedprox is agnostic of the sampling schemes and can yield similar improvement under either scenario.

Thank you! I will try it.

**Comment by tianboh** [comment]
Thanks for the work :) 
I have read the code, but there are some places I feel inconsistent with the paper.

- In the Algorithm 2 line 7, we are calculating the norm between local model and global model. But the code is using l2 norm for local model without considering global model. Taks [mnist/mclr.py line 40](https://github.com/litian96/FedProx/blob/master/flearn/models/mnist/mclr.py#L40) for example.

- I also checked the NLP experiments Shakespare, but I didn't find the regularization part in create_model. [shakespare/stacked_lstm.py create_model](https://github.com/litian96/FedProx/blob/master/flearn/models/shakespeare/stacked_lstm.py#L51)
