### ISSUE TITLE
Whether the difference calculation need to consider the proportion of the sample

### ISSUE THREAD

**Issue by guobbin** [litian96/FedProx#12]
Dear Tian:
Thank you very much for your code, I have a question:
Whether the difference calculation need to consider the proportion of data rather than simply adding?
44~45, https://github.com/litian96/FedProx/blob/master/flearn/trainers/fedprox.py
Thank you.

**Comment by litian96** [comment]
Yes, you can do that. We didn't do that for simplicity and we found that the two choices yield similar results---large gradient variance tends to correspond to worse convergence.

Please let me know if you have other questions!
