### ISSUE TITLE
The FEMNIST data generation

### ISSUE THREAD

**Issue by jyhong836** [litian96/FedProx#13]
In `my_sample.py` file for generating FEMNIST data, the `<` seems should be `>` in [line](https://github.com/litian96/FedProx/blob/0f9c2e8eda4133d1ba1da2d9fe4f53522eb51096/data/nist/data/my_sample.py#L86). Otherwise, the retrieved samples will be the same for the same class at the beginning. I checked the data files shared by google drive. There are indeed several same images for the identical class, each user.

**Comment by litian96** [comment]
Thanks for catching this typo. Yes, you are right! This generation process effectively results in the repartitioned FEMNIST data being a bit less statistically heterogeneous.
