### ISSUE TITLE
Tensorflow installation

### ISSUE THREAD

**Issue by schneider41** [litian96/FedProx#15]
Hi, I got this problem over Mac OS and windows:

`~ % pip install tensorflow-gpu==1.10`
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.10 (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==1.10

same with pip3

Did I missed anything?
Thanks

**Comment by Deehan1866** [comment]
Hey how did u solve it?! Thank u...

**Comment by Moon-Run** [comment]
> Hey how did u solve it?! Thank u...

Bro,Do u solve the problem?
