### ISSUE TITLE
what is the exact role of PerturbedGradientDescent in FedProx

### ISSUE THREAD

**Issue by Mohammad-Bakhtiari** [litian96/FedProx#18]
I studied your paper and code, and I'm troubled to clearly understand to what extent `PerturbedGradientDescent` optimizer contributes to your work. If you kindly explain to me what the following line does in your code, It may clear things up for me.
 https://github.com/litian96/FedProx/blob/0f9c2e8eda4133d1ba1da2d9fe4f53522eb51096/flearn/trainers/fedprox.py#L55 

Thank you in advance.

**Comment by litian96** [comment]
Thank you for your interest.

When you call `set_params`, it will assign `self.latest_model` to `v_star `(https://github.com/litian96/FedProx/blob/master/flearn/optimizer/pgd.py#L63-L64) (which is to set the global model w^t in the paper); and when we do local optimization, by using the pgd optimizer, we will update the parameters using gradients `\nabla F(w_k) + \mu (w_k - w^t)`, as enforced in the pgd optimizer (i.e., FedProx optimizer) class (https://github.com/litian96/FedProx/blob/master/flearn/optimizer/pgd.py#L29-L34).
