### ISSUE TITLE
Obtain \nabla h_k(w_t, w_t) in FedProx

### ISSUE THREAD

**Issue by mairtonbjr** [litian96/FedProx#19]
Hi, 

I studied your paper/code and I am trying to obtain \nabla h_k(w_t, w_t) to use as a local optimization criteria. In the `fedprox `and `pgd `codes, it is not clear to me where the gradients \nabla h_k(w, w_t) are evaluated. Could you help me with this? 

If I can understand where these gradients are evaluated, I could simply pass w_t, the `self.latest_model` in fedprox, to this function instead of using the local model.

Best Regards,
Mairton

**Comment by litian96** [comment]
Hi Mairton,

The way we obtain the gradient with the proximal term is to first pass the current global model w_t to the optimizer (https://github.com/litian96/FedProx/blob/master/flearn/trainers/fedprox.py#L55 will call https://github.com/litian96/FedProx/blob/master/flearn/optimizer/pgd.py#L59-L64), and then when applying the gradients, using \nabla h_k(w, w_t) (https://github.com/litian96/FedProx/blob/master/flearn/optimizer/pgd.py#L29-L36).

Hope this helps.

**Comment by litian96** [comment]
Hi Mairton,

Is your question answered?

**Comment by mairtonbjr** [comment]
Hi Tian,

Thank you very much for the answer, which I think answers my question. I am now trying to implement the optimization criteria from your paper using the \gamma_k^t and \nabla h_k(w_t, w_t) with GradientTape instead of using the number of epochs. 

Best Regards,
Mairton
