### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by roberthoenig** [litian96/FedProx#20]
I would like to use parts of the code of `FedProx` for my dissertation. In particular, I would like to use (https://github.com/litian96/FedProx/blob/master/data/synthetic_1_1/generate_synthetic.py)[generate_synthetic.py) to generate my own synthetic federated datasets.

Unfortunately, `FedProx` does not seem to have a license. This means that it has all rights reserved, and I am not allowed to use its code.

Can `FedProx` add an appropriate software license to this repository?

**Comment by litian96** [comment]
Thanks for your suggestions, we will add a license to it later. For now, feel free to use and modify it for your project without any restrictions.

**Comment by roberthoenig** [comment]
Great, thank you!
