### ISSUE TITLE
Why can't plot_fig2 after bash and showing no such a file?

### ISSUE THREAD

**Issue by rebear077** [litian96/FedProx#29]
![image](https://user-images.githubusercontent.com/51772538/163547346-784e9ac6-d439-4078-9975-bf4e93b88e81.png)
Problem is shown as above.
Where are those logs saved to?

**Comment by litian96** [comment]
Could you tell me more details like what exact bash instructions did you run?

**Comment by rebear077** [comment]
![image](https://user-images.githubusercontent.com/51772538/165907475-63188611-5cf5-4a30-ab60-da52685e6a62.png)
Thank you for reply. I just follow the tips in README, using the two lines in red box in sequence.

**Comment by litian96** [comment]
Could you double-check that there is a `log_synthetic/synthetic_iid_client10_epoch20_mu0` file generated? You might need to `mkdir log_synthetic` first before running `bash run_fedavg.sh xxx`.

**Comment by rebear077** [comment]
I got it. Thank you!

**Comment by shcccajdiajd** [comment]
> ![image](https://user-images.githubusercontent.com/51772538/163547346-784e9ac6-d439-4078-9975-bf4e93b88e81.png)问题如上所示。这些日志保存到哪里？

您好，可否加个联系方式，有几个问题想咨询一下，可以有偿，急！
