### ISSUE TITLE
No model of "'mnist.cnn"

### ISSUE THREAD

**Issue by cshjin** [litian96/FedProx#3]
Hi there, 
I do see you have the option of using CNN on the MNIST dataset. But I don't see the implementation in the model. 
Would you provide it later?

BTW, I was also on ICML this year, but was unable to attend the poster session. Would you put your poster on your homepage as well?

H.

**Comment by litian96** [comment]
Thanks for your interest! You could use any CNN architecture for MNIST. The most relevant one is: https://github.com/TalwalkarLab/leaf/tree/master/models/femnist of the [LEAF](https://leaf.cmu.edu/) benchmark. I am sure you could successfully get CNN running on MNIST following this piece of code.
The poster is up.

**Comment by cshjin** [comment]
Thanks. Issue closed.
