### ISSUE TITLE
AttributeError: 'Server' object has no attribute 'client_model'

### ISSUE THREAD

**Issue by gaolje** [litian96/FedProx#32]
After running this "bash run_fedprox.sh synthetic_iid 0 1 | tee log_synthetic/synthetic_iid_client10_epoch20_mu1"
![image](https://user-images.githubusercontent.com/105529434/175881645-7e325731-c85c-4f50-b18f-1b2884e7dfd7.png)
how should i solve this problem？

**Comment by nikhilbalwani** [comment]
How did you solve this problem?

**Comment by offaded** [comment]
同问，也遇到这个问题了
