### ISSUE TITLE
where reflects the  proximal term in you programme

### ISSUE THREAD

**Issue by SAGIN-Xu** [litian96/FedProx#6]
I check the loss function and others, but I fail to know how you use  proximal term

**Comment by litian96** [comment]
https://github.com/litian96/FedProx/blob/master/flearn/optimizer/pgd.py#L34

**Comment by SAGIN-Xu** [comment]
Thank you. My research interest is Federated learning，I hope to cooperate with you in the fetrue .





------------------ Original ------------------
